### ISSUE TITLE
Grid: Create 8x8 play area

### ISSUE THREAD

**Issue by imwithsam** [with-a-k/switchblock#4]
As a player,
When I click on Start
I will see an 8x8 grid that is randomly filled with 7 different objects
These 7 different objects will not start off with 3-in-a-row horizontally or vertically.

**Comment by with-a-k** [comment]
> player clicks start
> fill spaces via objects, but don't display them
> remove spaces in matches as if the game was ongoing, but don't award points
> drop spaces into holes if any, fill holes from top
> if the board enters a loss state, regenerate the board
> once the board is stable, with possible moves, then display the board
